config/routes.rb
BakeShop::Application.routes.draw do
  
  
  
  get "user/login" => "sessions#new"
  get "user/logout" => "sessions#destroy", :as => "logout"
  get "pages/services"
  get "pages/help"
  get "pages/menu"
  get "pages/products(/:prod)" => "pages#products", :as => 'products'
  post "pages/home"
  
  get "users/signup" => "users#new"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root :to => 'pages#home'
  
  
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'digest/md5'
  
  attr_accessible :password_confirmation, :name, :email, :password, :username
  before_save :encrypt_password
  
  
  validates :name,  :presence => true,
                    :length => { :maximum => 25}

  validates :username,  :presence => true,
                        :length => { :maximum => 25},
                        :uniqueness => {:case_sensitive => false}                    
                    
  validates :email, :presence => true,
                    :uniqueness => {:case_sensitive => false}
                    
  validates :password, :presence => true, 
            :confirmation => true,
            :length => {:within => 6..40}
            
  
  def self.authenticate(username, password)
    user = User.find_by_username(username)
    
    if user && user.password == Digest::MD5.hexdigest(password)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    self.password = Digest::MD5.hexdigest(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private
  def check_login
      if !session[:user_id]
        flash[:status] = FALSE
        flash[:alert] = "You need to be login first"
        
        redirect_to user_login_path
      else
        @user = User.find[session[:user_id]]
        $user_username = @user.username
      end
  end

  def checklogin
      if !current_user
        flash[:status] = FALSE
        flash[:alert] = "You need to be logged in first"
        
        redirect_to user_login_path
      end
  end


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def sign_in_check(user)
    #user = User.authenticate(user.username, user.password)
    #@tiago = user.username
    session[:user_id] = user.id
    session[:username] = user.username
    #session[:expires_at] = Time.now + 60.minutes
    #request.session_options[:expire_after] = 2.minutes
  end 
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_filter :checklogin, :only => [:products]
  
  def home
    @gender = params[:gender]
    @email = params[:email]
  end
  
  def services
    @users = User.all
    @column_names = User.column_names
  end
  
  def menu
    
  end
  
  def products
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:session][:username], params[:session][:password])
    
    if user
      sign_in_check user #session[:user_id] = user.id
      redirect_to root_path, :notice => "logged in"
    else
      flash.now.alert = "Invalid username or password"
      render 'new'
    end
    
  end
  
  def destroy
    session[:user_id] = nil
    session[:username] = nil
    redirect_to root_path, :notice => "logged out"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def new
    @user = User.new
    @title = "User Sign Up"    
  end
   
  def create
    
    @user = User.new(params[:user])
    
    
    if @user.save
      #flash[:status] = true
      #flash[:alert] = "You have successfully signed up!!"
      
      sign_in_check @user
      redirect_to root_path, :flash => { :success => "Welcome to the Bakeshop"}
    else
      @title = "User Sign Up" 
      render 'new'
    end  
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      redirect_to pages_services_path, :notice => "Update Successful"
    else
      render "edit"
    end
  end  
  
  def show
    @profile = User.find(params[:id])
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to pages_services_path, :notice => "Delete Successful"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_name
    name = User.find(session[:user_id])
    name = name.name
  end



end

app/helpers/pages_helper.rb
module PagesHelper
  def logo
    image_tag("logo.jpg", :alt => "bakeshop logo", :class => "round")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def login_message
    html = '<div>'
    
    if flash[:status] == true
      html += flash[:alert]
    elsif flash[:status] == false
      flash[:alert].each do |error|
        html += error
      end
    end
    html += '</div>'
    
    return html.html_safe
  end
  


  
end

app/views/layouts/_footer.html.erb
		<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Friends</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside class="footer-segment">
							<h4>Awesome Stuff</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside class="footer-segment">
							<h4>Coolness</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside class="footer-segment">
							<h4>Blahdyblah</h4>
								<p>&copy; 2010 <a href="#">yoursite.com</a> Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. </p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>

app/views/layouts/_header.html.erb
<header><!-- header -->
	<div id="headerlogo"><%= image_tag("kookycook.png")%></div>
	<h1><%= link_to "Kooky Cook", '#' %></h1>
	<h2>Your cute and compelling tag line goes here</h2>
</header><!-- end of header -->

app/views/layouts/_menu.html.erb
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", '#' %></li>
				<li><%= link_to "Recipes", '#' %></li>
				<li><%= link_to "Products", products_path %></li>
				
				<li><%= link_to "Services", pages_services_path %></li>
				
				<li><%= link_to "Contact Us", '#' %></li>
				<%if current_user %>
					<li><%= "Hi, " + user_name %></li>
				<% else %>
				<li><%= link_to "Login", user_login_path %></li>
				
				<% end %>
			</ul>
		</div>
	</nav><!-- end of top nav -->

app/views/layouts/_sidebar.html.erb
		<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<ul>
						<li><%= link_to "Create Meals", '#' %></li>
						<li><%= link_to "Chat With Friends", '#' %></li>
						<li><%= link_to "Order Now", '#' %></li>
						
						<% if current_user %>
							<li><%= link_to "Logout Now", logout_path %></li>
						<% else %>
							<li><%= link_to "Sign Up Now", users_signup_path %></li>
						<% end %>
					</ul>
					
				<h3>Sponsors</h3>
					<%= image_tag("adv.jpg") %></ br>
					<%= image_tag("adv.jpg") %>

				<h3>Connect With Us</h3>
					<ul>
						<li><%= link_to "Youtube", "http://www.youtube.com", :target => "_blank" %></li>
						
					</ul>

		</aside><!-- end of sidebar -->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/sun/trunk/html5.js"></script>
<![end]-->
<%= stylesheet_link_tag 'blueprint/screen', :media=> 'screen'%>
<%= stylesheet_link_tag 'blueprint/print', :media=> 'print'%>

<!--[if lt IE8]><%= stylesheet_link_tag 'blueprint/ie' %><![end]-->
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BakeShop</title>
		<%= stylesheet_link_tag 'styles', :media=> 'screen'%>
		<%= stylesheet_link_tag 'print', :media=> 'print'%>
		
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper"><!-- #wrapper -->
			<%= render 'layouts/menu'%>
			<%= render 'layouts/header'%>
			<section id="main">
				<%= render 'layouts/sidebar'%>
				<section id="content"><!-- #content -->

			<% flash.each do |key, value|%>
				<div class="flash <%= key %>"><%= value %></div>
			
			<% end %>

					
					<%= yield %>	
				<% if session[:username] == 'admin'%>
					<div class="debug">
						
							<% params.each do |key, value|  %>
								<% if key != "utf8" && key != "authenticity_token"%>
									<%= "#{key} = #{value}"%><br />
								<% end %>
								
							<% end %>
							<%= "Session username: " + session[:username].to_s%>
						
					</div>
				<% end %>	
				</section>
			</section>
			
			<%= render 'layouts/footer'%>
		</div>
	</body>
</html>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>pleasebangmywife.com </p>

<p>
joty7700:7700clb
kdawg040:coolkyle</p>

app/views/pages/home.html.erb
<h1>Home</h1>

	<% if session[:username] == "admin"%>
		<p>pleasebangmywife.com </p>
		
		<p>
		joty7700:7700clb<br>kdawg040:coolkyle</p>
		
		<%= form_tag do %>
			<p><%= select_tag "params", options_for_select(params, params[:action]) %></p>
			
			<p>
				<%= radio_button_tag 'gender', 'male', @gender=="male" %>
				<%= label_tag 'gender_male', "Male" %><br />
				<%= radio_button_tag 'gender', 'female', @gender=="female" %>
				<%= label_tag 'gender_female', "Female" %><br/>
				<%= email_field_tag "email", @email, :placeholder => "Place your email here"%>
				
				<p>
					<%= submit_tag "Submit"%>
				</p>
			</p>
		<% end %>
		
	<% else current_user %>
		This sample was created by Carl William Tablante. As of now the working links are as follows:
		<p>
		<ul>
			<li>HOME - This page is static, contains information about the site</li>
			<li>PRODUCTS - This page is static. It can't be accessed unless you're logged in</li>
			<li>SERVICES - This page shows a basic CRUD. It can't be accessed unless you're logged in</li>
			<li>LOGIN - Login page. This demonstrates user authentication.</li>
			<li>SIGN UP NOW - Registration page. This demonstrates user registration</li>
			<li>LOGOUT NOW - Logs you out</li>
		</ul>
		</p>
	<% end %>

app/views/pages/menu.html.erb
<h1>Menu</h1>

app/views/pages/products.html.erb
<p><% params[:prod]%></p>


<% if params[:prod] == nil %>
<h1>Products</h1>
<table class = "thumbnails">
	<tr>
		<td><%= image_tag("cake.jpg", :class => "thumbnail") %></td>
		<td><%= image_tag("muffin.jpg", :class => "thumbnail") %></td>
		<td><%= image_tag("brownies.jpg", :class => "thumbnail") %></td>
	</tr>
	<tr>
		<td><%= link_to "Cakes", products_path(:prod => "cake") %></td>
		<td><%= link_to "Muffins", products_path(:prod => "muffin")%></td>
		<td><%= link_to "Brownies", products_path(:prod => "brownies")%></td>
	</tr>
</table>
<% else %>
<h1><%= params[:prod].capitalize %></h1>

<% end %>

app/views/pages/services.html.erb
<h1>Shows all users</h1>

<% if current_user %>

	<table border="1">
	<% @column_names.each do |column_name| %>
		<% if column_name == "name" || column_name !== "username" || column_name !== "updated_at"%>
			<td>
				<strong><%= column_name.capitalize %></strong>		
			</td>
		<% end %>
	<% end %>
			
	<% @users.each do |user| %>
	
	
		<tr>
			<td><%= user.name%></td>
			<td><%= user.username%></td>
			<td><%= user.email%></td>
			<td><%= link_to "edit", edit_user_path(user)%></td>
			<td><%= link_to "Show", user_path(user)%></td>			
		</tr>
	<%end%>	
	</table>

	<% else %>
	
		<div id="myCarousel" class="carousel slide" >
		  <!-- Carousel items -->
		  <div class="carousel_image">
			  <div class="carousel-inner" >
	
			    <div class="active item"><%= image_tag("cake.jpg") %></div>
			    <div class="item"><%= image_tag("muffin.jpg") %></div>
			    <div class="item"><%= image_tag("brownies.jpg") %></div>
			  </div>
		  </div>
		  <!-- Carousel nav -->
		  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>


<% end %>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
	<div id = "error_explanation">
		<h2>
			<%= pluralize(@user.errors.count, "error")%>
			prohibited this user from being saved:
		</h2>
		<p>There were problems with the following fields:</p>
		<ul>	
			<% @user.errors.full_messages.each do |message|%>
				<li><%= message %></li>
			<% end %>
		</ul>
		
			
		
	</div>



<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= form_for @user do |f| %>
	<%= render 'shared/error_message' %>
	<p>
		<%= f.text_field :name%><br/>
		<%= f.label :name %><br/>
	</p>
	
	<p>
		<%= f.text_field :username %><br/>
		<%= f.label :username%><br/>
	</p>
	
	<p>
		<%= f.email_field :email%><br/>
		<%= f.label :email %><br/>
	</p>
	
	<p> <%= f.submit "Update" %></p>


<% end%>

app/views/users/new.html.erb
<h1><%= @title %></h1>


<%= form_for @user do |f| %>
		<%= render 'shared/error_message' %>
	<p>
		<p>
			<%= f.text_field :name%><br/>
			<%= f.label :name %><br/>
		</p>
		
		<p>
			<%= f.text_field :username, :placeholder => "login name"%><br/>
			<%= f.label :username%><br/>
		</p>
		
		<p>
			<%= f.email_field :email, :placeholder => "Email"%><br/>
			<%= f.label :email %><br/>
		</p>
		
		<p>
			<%= f.password_field :password%><br/>
			<%= f.label :password%><br/>
		</p>
		
		<p>
			<%= f.password_field :password_confirmation %><br/>
			<%= f.label :password_confirmation %>
		</p>
		
		<p>
			<%= submit_tag "Sign up"%>
		</p>
	</p>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>


<p>Name: <%= @profile.name%></p>

<p>Userame: <%= @profile.username%></p>

<p>Email: <%= @profile.email%></p>

<p>
<%= button_to "Delete", user_path(@profile), :method => "delete", :data => {:confirm => "Are you sure?"} %>
</p>